version: '3'
x-airflow-common:
  &airflow-common
  build:
    context: ./containers/airflow/
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW_CONN_POSTGRES_DEFAULT: postgres://airflow:airflow@postgres:5432/airflow
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://webserver:8080/execution
    AIRFLOW__CORE__SECRET_KEY: fef8bfc69e80411c6ee933a8ba1ab04551768a650e4122589a13b710a5ae6757
    AIRFLOW__WEBSERVER__SECRET_KEY: fef8bfc69e80411c6ee933a8ba1ab04551768a650e4122589a13b710a5ae6757
    AIRFLOW__API__SECRET_KEY: fef8bfc69e80411c6ee933a8ba1ab04551768a650e4122589a13b710a5ae6757
    AIRFLOW__API__AUTH_JWT_SECRET: fef8bfc69e80411c6ee933a8ba1ab04551768a650e4122589a13b710a5ae6757
    AIRFLOW_CONN_AWS_DEFAULT: '{"conn_type": "aws", "extra": {"aws_access_key_id": "minio", "aws_secret_access_key": "minio123", "region_name": "us-east-1", "endpoint_url": "http://minio:9000"}}'
    AIRFLOW_CONN_SPARK_CONN: '{"conn_type": "spark", "host": "spark://192.168.0.1", "port": 7077}'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./visualization:/opt/airflow/visualization
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests
    - ./temp:/opt/airflow/temp
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./containers/upstream:/docker-entrypoint-initdb.d
      - ./data:/input_data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"

  airflow-webserver:
    <<: *airflow-common
    container_name: webserver
    command: api-server
    ports:
      - 8080:8080
    healthcheck:
      test:
        [
          "CMD-SHELL", # Change CMD to CMD-SHELL
          "bash -c 'curl --fail http://localhost:8080/'" # Use bash -c to run curl
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: scheduler
    command: scheduler
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'airflow jobs check --job-type SchedulerJob --hostname \"$${HOSTNAME}\"'" # Use bash -c
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    container_name: dag-processor
    command: dag-processor
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'airflow jobs check --job-type DagProcessorJob --hostname \"$${HOSTNAME}\"'"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'  
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

